### ISSUE TITLE
Example with VerkoopSjabloon

### ISSUE THREAD

**Issue by Leondejoode** [iwd-nl/snelstart-php#13]
Can you please provide me an example with Verkoopordersjabloon?

I can't get it to work.

Thank you in advance!

**Comment by manuelderuiter** [comment]
Hi Leon,

Try: https://github.com/iwd-nl/snelstart-php/tree/dev/verkoopordersjabloon

**Comment by Leondejoode** [comment]
Hi Manual,

That works, thank you very much!
