### ISSUE TITLE
VerkoopOrderStatus appears to be missing from Verkooporder

### ISSUE THREAD

**Issue by dfsoeten** [iwd-nl/snelstart-php#38]
Hi there, 

The [`VerkoopOrder`](https://github.com/iwd-nl/snelstart-php/blob/master/src/Model/V2/Verkooporder.php) seems to be missing the `verkoopOrderStatus` property. See [schema definition](https://b2bapi-developer.snelstart.nl/docs/services/5c18d0cdd21b99cfccdde8eb/operations/v2-verkooporders-POST?&pattern=verkooporder):
```
{
   ...,
   "verkoopOrderStatus": {
      "description": "Status van de order. Als deze niet is opgegeven wordt de default waarde InBehandeling gebruikt.",
      "enum": [
        "InBehandeling",
        "Uitgevoerd",
        "Service"
      ],
      "type": "string"
    },
    ...
}
```

Is this intentional?

**Comment by manuelderuiter** [comment]
Hi,

No, not intentional. You can add it if you want.
